### ISSUE TITLE
Is this the correct repo for neo4jrb.io?

### ISSUE THREAD

**Issue by andrewhavens** [neo4jrb/neo4jrb.github.io#2]
In the tutorial video on the website, it mentions a Rails generator template at http://neo4jrb.io/neo4j/neo4j.rb. I'm trying to find the source code for that file but it doesn't seem to be in this repository. The link on the homepage points to this repository. Is this the correct repository for the website? Or is this an old repo?

**Comment by cheerfulstoic** [comment]
That would be in the neo4jrb/neo4j repository in the gh_pages branch.  It's a quirk of how GitHub pages works.  The domain goes to this repo but if you have other repos in you user/group account with a gh_pages branch then subdirectories use that

**Comment by andrewhavens** [comment]
Ah okay. Strange.

**Comment by cheerfulstoic** [comment]
Back to my computer now.  Here's a link to the file:

https://github.com/neo4jrb/neo4j/blob/gh-pages/neo4j.rb

Let me know if you have any other problems!
